### ISSUE TITLE
Appropiate for Ingenico Move 5000 terminal

### ISSUE THREAD

**Issue by RamoramaInteractive** [Ingenico-ePayments/connect-sdk-python3#1]
Can I use this SDK to connect with a Move 5000 terminal?

**Comment by IngenicoEPayments** [comment]
These SDKs are meant to connect to the Ingenico Connect API to process online payments, primarily in e-commerce environments. The SDK isn't mean to be used on combination with any Ingenico terminals. You might be able to find more information regarding terminals at https://developer.ingenico.com.
