### ISSUE TITLE
Sandbox GlobalCollectException

### ISSUE THREAD

**Issue by MichaIncentro** [Ingenico-ePayments/connect-sdk-python3#2]
None of the provided examples seem to work. All create payments methods result in a server error on the Ingenico side of things. My code has worked previously so it looks like this isn't a fault on our side of things.

Is the error below a familiar error?

````
ingenico.connect.sdk.global_collect_exception.GlobalCollectException: the Ingenico ePayments platform returned an error response; status_code=500; response_body='{
   "errorId" : "5ed0e233608a785f2b40efa5ac1d4a43",
   "errors" : [ {
      "code" : "11000400",
      "requestId" : "1034",
      "message" : "Server time-out",
      "httpStatusCode" : 500
   } ]
}'
````

**Comment by psteenst** [comment]
Dear Michalcentro,

Many thanks for raising this. We indeed had an issue on our sandbox environment, causing the HTTP 500 error you posted above.
It should be fixed by now. Would you be so kind to let me know whether it also works for you?

Kind regards,
Petra
Ingenico ePayments

**Comment by MichaIncentro** [comment]
It's working again. Thank you.
